### ISSUE TITLE
Move lesson to Carpentries Incubator

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/medical-image-processing#33]
Ideally we should move this lesson the carpentries incubator, it will help make the lesson more visible and have more impact.

You can submit it by opening an issue [through this link](https://github.com/carpentries-incubator/proposals/issues/new?assignees=tobyhodges&labels=proposal&projects=&template=lesson_proposal.yml&title=%5BProposal%5D%3A+)

**Comment by drcandacemakedamoore** [comment]
The issue has been opened, emailed and discussed with the head of
curriculum for weeks already. They know to the point they apologized for
not moving faster

Op vr 15 nov. 2024 07:33 schreef Sven van der Burg ***@***.***

**Comment by svenvanderburg** [comment]
@drcandacemakedamoore Oh, I did not now that and did not check properly, sorry 😐 Yes, I know it takes long, there is nothing we can do about that.

**Comment by drcandacemakedamoore** [comment]
Done.
